
import json
from datetime import datetime, timezone
from enum import Enum
from typing import Dict, List, Optional, Type, Union

from pydantic import BaseModel, Field

class SupabaseConfig(BaseModel):
    URL: str
    KEY: str


class _TableIDConfig(BaseModel):
    USER: str
    GAUTH: str
    MESSAGE: str


class _UserIDConfig(BaseModel):
    TELEGRAM: str
    EMAIL: str


class ConstantIDConfig(BaseModel):
    TABLE_IDS: _TableIDConfig
    USER_IDS: _UserIDConfig
    ID_COLUMN_NAME: str

class GAuthTable(BaseModel):
    access_token: str
    refresh_token: str
    token_expiry: Optional[str] = None
    token_uri: str
    user_agent: Optional[str] = None


# class UserTable(BaseModel):
#     username: Optional[str] = None
#     telegram_id: Optional[int] = None
#     email_id: Optional[str] = None


class Tables(Enum):
    """Tables available in the database."""

    AGENTS = "agents"
    AGENTS__id = "id"
    AGENTS__first_message = "first_message"
    AGENTS__bird_channel_id = "bird_channel_id"
    AGENTS__telegram_chat_id = "telegram_chat_id"

    USERS = "users"
    USERS__id = "id"
    USERS__created_at = "created_at"
    USERS__phone_number = "phone_number"
    USERS__telegram_uid = "telegram_uid"
    USERS__birthday = "birthday"

    ROOMS = "rooms"
    ROOMS__id = "id"
    ROOMS__created_at = "created_at"
    ROOMS__user_id = "user_id"
    ROOMS__agent_id = "agent_id"

    MESSAGES = "messages"
    MESSAGES__id = "id"
    MESSAGES__room_id = "room_id"
    MESSAGES__created_at = "created_at"
    MESSAGES__from_user = "from_user"
    MESSAGES__message = "message"



def utc_now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


class AgentModel(BaseModel):
    id: Optional[int | str] = Field(
        default=None, description="Auto-generated by database"
    )
    first_message: Optional[str]
    telegram_chat_id: Optional[str]
    bird_channel_id: Optional[str]


class UserModel(BaseModel):
    id: Optional[int | str] = Field(
        default=None, description="Auto-generated by database"
    )
    created_at: datetime = Field(default_factory=utc_now)
    phone_number: Optional[str]
    # birthday: Optional[datetime]
    telegram_uid: Optional[str]



class RoomModel(BaseModel):
    id: Optional[int | str] = Field(
        default=None, description="Auto-generated by database"
    )
    created_at: datetime = Field(default_factory=utc_now)
    user_id: int
    agent_id: int


class MessageModel(BaseModel):
    id: Optional[int | str] = Field(
        default=None, description="Auto-generated by database"
    )
    room_id: int
    created_at: datetime = Field(default_factory=utc_now)
    from_user: bool
    message: str

TableModel = Union[UserModel, AgentModel, MessageModel, RoomModel]

TABLE_MODEL_MAP = {
    Tables.USERS.value: UserModel,
    Tables.ROOMS.value: RoomModel,
    Tables.AGENTS.value: AgentModel,
    Tables.MESSAGES.value: MessageModel,
}
