database_tables:
  - name: "food"
    table_type: "row"
    description: "food, nutrition, and/or calorie data"
    llm_control: true
    columns:
      - name: "start_time"
        description: "specified start time the user stated (in the ISO 8601 format 'YYYY-MM-DDTHH:MM:SSZ' or 'YYYY-MM-DDTHH:MM:SS±HH:MM')"
        datatype: "timestamp"
      - name: "end_time"
        description: "specified end time the user stated (in the ISO 8601 format 'YYYY-MM-DDTHH:MM:SSZ' or 'YYYY-MM-DDTHH:MM:SS±HH:MM')"
        datatype: "timestamp"
      - name: "food"
        description: "the name of the food or dish"
        datatype: "string"
      - name: "meal_type"
        description: "the type of meal this is (e.g. 'dinner', 'breakfast', 'lunch', 'snack')"
        datatype: "string"
      - name: "calories"
        description: "the exact or estimated amount of calories in this meal"
        datatype: "integer"
      - name: "protien"
        description: "the exact or estimated amount of protien (in grams) in this meal"
        datatype: "integer"
      - name: "fat"
        description: "the exact or estimated amount of fat (in grams) in this meal"
        datatype: "integer"
      - name: "carbs"
        description: "the exact or estimated amount of carbs (in grams) in this meal"
        datatype: "integer"
      - name: "notes"
        description: "add any other important information that is given, but not captured otherwise, here"
        datatype: "string"
  - name: "workout"
    table_type: "row"
    description: "workout data"
    llm_control: false
    columns:
      - name: "start_time"
        description: "specified start time the user stated (in the ISO 8601 format 'YYYY-MM-DDTHH:MM:SSZ' or 'YYYY-MM-DDTHH:MM:SS±HH:MM')"
        datatype: "timestamp"
      - name: "end_time"
        description: "specified end time the user stated (in the ISO 8601 format 'YYYY-MM-DDTHH:MM:SSZ' or 'YYYY-MM-DDTHH:MM:SS±HH:MM')"
        datatype: "timestamp"
      - name: "workout"
        description: "the general name of the workout"
        datatype: "string"
      - name: "calories"
        description: "the exact or estimated amount of calories burned during this workout"
        datatype: "integer"
      - name: "notes"
        description: "add any other important information that is given, but not captured otherwise, here"
        datatype: "string"
  - name: "work"
    table_type: "row"
    description: "work, college, and/or studying data"
    llm_control: true
    columns:
      - name: "start_time"
        description: "specified start time the user stated (in the ISO 8601 format 'YYYY-MM-DDTHH:MM:SSZ' or 'YYYY-MM-DDTHH:MM:SS±HH:MM')"
        datatype: "timestamp"
      - name: "end_time"
        description: "specified end time the user stated (in the ISO 8601 format 'YYYY-MM-DDTHH:MM:SSZ' or 'YYYY-MM-DDTHH:MM:SS±HH:MM')"
        datatype: "timestamp"
      - name: "work"
        description: "the description of the work, college, and/or studying done"
        datatype: "string"
      - name: "notes"
        description: "add any other important information that is given, but not captured otherwise, here"
        datatype: "string"
  - name: "sleep"
    table_type: "row"
    description: "sleep data"
    llm_control: true
    columns:
      - name: "start_time"
        description: "specified start time the user stated (in the ISO 8601 format 'YYYY-MM-DDTHH:MM:SSZ' or 'YYYY-MM-DDTHH:MM:SS±HH:MM')"
        datatype: "timestamp"
      - name: "end_time"
        description: "specified end time the user stated (in the ISO 8601 format 'YYYY-MM-DDTHH:MM:SSZ' or 'YYYY-MM-DDTHH:MM:SS±HH:MM')"
        datatype: "timestamp"
      - name: "quality"
        description: "the description of the quality of sleep described"
        datatype: "string"
      - name: "notes"
        description: "add any other important information that is given, but not captured otherwise, here"
        datatype: "string"
  - name: "events"
    table_type: "row"
    description: "events data you would put on a calendar (if not anything else)"
    llm_control: true
    columns:
      - name: "start_time"
        description: "specified start time the user stated (in the ISO 8601 format 'YYYY-MM-DDTHH:MM:SSZ' or 'YYYY-MM-DDTHH:MM:SS±HH:MM')"
        datatype: "timestamp"
      - name: "end_time"
        description: "specified end time the user stated (in the ISO 8601 format 'YYYY-MM-DDTHH:MM:SSZ' or 'YYYY-MM-DDTHH:MM:SS±HH:MM')"
        datatype: "timestamp"
      - name: "title"
        description: "the title of the event/action"
        datatype: "string"
      - name: "location"
        description: "the location of the event/action"
        datatype: "string"
      - name: "notes"
        description: "add any other important information that is given, but not captured otherwise, here"
        datatype: "string"
  - name: "notes"
    table_type: "row"
    description: "notes to remember"
    llm_control: true
    columns:
      - name: "title"
        description: "the title of the note (make one if not obvious)"
        datatype: "string"
      - name: "note"
        description: "the notes to remember"
        datatype: "string"
intent_llm_config:
  provider: "google"
  name: "gemini-1.5-flash"
