
API_CONFIG:
  MESSAGING:
    TELEGRAM:
      TELEGRAM_BOT_TOKEN: 6827949829:AAHZqp0GeDuerBYTJ74ImCjPjS1kBVsZcJ4
    BIRD:
      BIRD_API_URL: https://api.bird.com
      BIRD_ORGANIZATION_ID: 3a97bb9d-cc49-4478-9f3f-5d53320767cc
      BIRD_WORKSPACE_ID: f52c1e19-7e3f-4a2c-828c-e129362c3b9c
      BIRD_API_KEY: YsARBpP172UpN1a3S0qdHWioRB24fOBKRa3A
      BIRD_SIGNING_KEY: ILovePotatoesAndAvocadoesUnderTheStars49
      BIRD_CHANNEL_ID: 946f4f9d-21c0-495e-b59d-5f3704deb11b'
  DATABASE:
    SUPABASE:
      URL: https://oncnddivofazzucihfce.supabase.co
      KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uY25kZGl2b2Zhenp1Y2loZmNlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxNDMyMjc1NCwiZXhwIjoyMDI5ODk4NzU0fQ.elTGW0lY0APLGsP5Kx6pzF9YVAnYXgRrmhPHL_95LMI
    REDIS:
      URL: redis://127.0.0.1
  LLM:
    GEMINI:
      API_KEY: ""
    GROQ:
      API_KEY: ""
    OPENAI:
      API_KEY: ""
    ANTHROPIC:
      API_KEY: ""
  WEB_ACCESS:
    GOOGLE:
      GOOGLE_API_KEY: AIzaSyDC9IFtL5VrXspr1HEIkI88K9xSBaFwXTw
      GOOGLE_CLIENT_ID: 277806072672-4dnp0sbeh2eu3ght4gqhjji9tt2uip5l.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      GOOGLE_AUTH_SCOPE:
        - https://www.googleapis.com/auth/calendar
        - https://www.googleapis.com/auth/drive.file
      CALENDAR:
        CALENDAR_NAME: Life Tracking
        CALENDAR_DESCRIPTION: Use this calendar to track what you do day to day.
      DRIVE:
        FOLDER_NAME: Life Tracking
        FILE_NAME_FORMAT: "%m_%d_%y %H:%M"

AGENT_CONFIG: 
  ID: 1
  NAME: Nick
  PROMPT: You are boyfriend
  DEFAULT_FIRST_MESSAGE: # The default message the Zootopian sends if you message it first
  BEHAVIORS:
    INTENT_DETECTION:
      MODEL: gpt 4o
    HUMAN_LIKE_MEMORY:
      MODEL: claude 3.5


